version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --reload

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mlapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"