version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mlapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    depends_on:
      - db
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["./wait-for-it.sh", "db:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]
    # entrypoint: tail -f /dev/null # dev only
