"""add new column to data_split_configs: features and target

Revision ID: 2135c976e8f9
Revises: 517fb355b289
Create Date: 2024-09-27 07:32:22.257777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2135c976e8f9'
down_revision = '517fb355b289'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_split_configs', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('data_split_configs', sa.Column('target', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_split_configs', 'target')
    op.drop_column('data_split_configs', 'features')
    # ### end Alembic commands ###
