"""add into two tables, model: is_default; data_split_config: missing value handling related column

Revision ID: 4f260cd3ec05
Revises: 2135c976e8f9
Create Date: 2024-10-03 13:37:31.493541

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '4f260cd3ec05'
down_revision = '2135c976e8f9'
branch_labels = None
depends_on = None

missing_data_strategy_enum = sa.Enum('do_nothing', 'fill_mean', 'fill_median', 'fill_most_frequent', 'remove_rows', 'replace_constant', name='missingdatastrategy')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    missing_data_strategy_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('data_split_configs', sa.Column('missing_data_strategy', missing_data_strategy_enum, nullable=True))
    op.add_column('models', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('data_split_configs', sa.Column('constant_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'is_default')
    op.drop_column('data_split_configs', 'missing_data_strategy')
    op.drop_column('data_split_configs', 'constant_value')
    missing_data_strategy_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
    # ### commands auto generated by Alembic - please adjust! ###
