"""init alembic; add model, data_split_config

Revision ID: 517fb355b289
Revises: 
Create Date: 2024-09-27 06:01:09.598513

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '517fb355b289'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_split_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('train_size', sa.Float(), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_split_configs_filename'), 'data_split_configs', ['filename'], unique=False)
    op.create_index(op.f('ix_data_split_configs_id'), 'data_split_configs', ['id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('algorithm', sa.String(), nullable=True),
    sa.Column('model_file', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_data_split_configs_id'), table_name='data_split_configs')
    op.drop_index(op.f('ix_data_split_configs_filename'), table_name='data_split_configs')
    op.drop_table('data_split_configs')
    # ### end Alembic commands ###
