"""create algorithm table

Revision ID: 63f4a35af71a
Revises: 64b77e83ea9f
Create Date: 2024-10-12 11:21:04.017344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f4a35af71a'
down_revision = '64b77e83ea9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('default_hyperparameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_algorithms_id'), 'algorithms', ['id'], unique=False)
    op.create_index(op.f('ix_algorithms_name'), 'algorithms', ['name'], unique=True)
    op.add_column('models', sa.Column('algorithm_id', sa.Integer(), nullable=True))
    op.create_foreign_key('models_algorithm_id_fkey', 'models', 'algorithms', ['algorithm_id'], ['id'])
    op.drop_column('models', 'algorithm')
    op.drop_column('models', 'is_default')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('models', sa.Column('algorithm', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('models_algorithm_id_fkey', 'models', type_='foreignkey')
    op.drop_column('models', 'algorithm_id')
    op.drop_index(op.f('ix_algorithms_name'), table_name='algorithms')
    op.drop_index(op.f('ix_algorithms_id'), table_name='algorithms')
    op.drop_table('algorithms')
    # ### end Alembic commands ###
