"""add metrics to model

Revision ID: 64b77e83ea9f
Revises: 4f260cd3ec05
Create Date: 2024-10-11 08:10:21.712088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64b77e83ea9f'
down_revision = '4f260cd3ec05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('config_id', sa.Integer(), nullable=True))
    op.add_column('models', sa.Column('accuracy', sa.Float(), nullable=True))
    op.add_column('models', sa.Column('f1_score', sa.Float(), nullable=True))
    op.add_column('models', sa.Column('status', sa.String(), nullable=True))
    op.create_foreign_key('models_config_id_fkey', 'models', 'data_split_configs', ['config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('models_config_id_fkey', 'models', type_='foreignkey')
    op.drop_column('models', 'status')
    op.drop_column('models', 'f1_score')
    op.drop_column('models', 'accuracy')
    op.drop_column('models', 'config_id')
    # ### end Alembic commands ###
