"""add project_name to models

Revision ID: cf132ad4c29f
Revises: 63f4a35af71a
Create Date: 2024-10-22 19:08:53.066469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf132ad4c29f'
down_revision = '63f4a35af71a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('project_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'project_name')
    # ### end Alembic commands ###
